import { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import {
  Card,
  AvatarWrapper,
  Text,
  TextLight,
  DetailWrapper,
  RatingWrapper,
  SwiperContainer,
} from "../styled/Home";
import { Swiper, SwiperSlide } from "swiper/react";
import "swiper/css";
import { Autoplay, Pagination, Navigation } from "swiper";
import Link from "next/link";

type User = {
  Id: number;
  UserName: string;
  FirstName: string;
  FirstName_ar: string;
  LastName: string;
  LastName_ar: string;
  SpecialtyTitle_en: string;
  SpecialtyTitle_ar: string;
  Rating: number;
  ProfilePic: string;
  ProfilePicThumbnail: string;
};

const Home = ({ doctors }: { doctors: [User] }) => {
  return (
    <>
      <Head>
        <title>List</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <SwiperContainer>
          <Swiper
            spaceBetween={10}
            slidesPerView='auto'
            breakpoints={{
              640: {
                width: 640,
                slidesPerView: 2,
              },
              360: {
                width: 360,
                slidesPerView: 1,
              },
            }}
            centeredSlides={true}
            modules={[Autoplay]}
            autoplay={{
              disableOnInteraction: true,
            }}
            loop
          >
            {doctors.map((doctor, index) => (
              <SwiperSlide key={doctor.FirstName + index.toString()}>
                <Link href={`/profile/${doctor.Id}`}>
                  <Card>
                    <AvatarWrapper>
                      {doctor.ProfilePic ? (
                        <Image
                          src={`https://s3-eu-west-1.amazonaws.com/curaapps/${doctor.ProfilePic}`}
                          width={200}
                          height={200}
                          alt='avatar'
                        />
                      ) : (
                        <Image
                          src='/avatar.png'
                          width={200}
                          height={200}
                          alt='avatar'
                        />
                      )}
                    </AvatarWrapper>
                    <DetailWrapper>
                      <Text>{doctor.FirstName + " " + doctor.LastName} </Text>
                      <TextLight>{doctor.SpecialtyTitle_en}</TextLight>
                      <RatingWrapper>
                        <svg
                          width='21'
                          height='21'
                          viewBox='0 0 21 21'
                          fill='none'
                          xmlns='http://www.w3.org/2000/svg'
                        >
                          <path
                            fill-rule='evenodd'
                            clip-rule='evenodd'
                            d='M10.5 3C8.8032 3 8.64278 5.95544 7.63259 6.99965C6.6224 8.04385 3.48183 6.84993 3.04549 8.70336C2.61006 10.5577 5.43529 11.1869 5.78364 12.7779C6.13381 14.3688 4.40769 16.6041 5.88264 17.7165C7.35759 18.828 8.94529 16.3123 10.5 16.3123C12.0547 16.3123 13.6424 18.828 15.1173 17.7165C16.5923 16.6041 14.8671 14.3688 15.2164 12.7779C15.5656 11.1869 18.3899 10.5577 17.9545 8.70336C17.5191 6.84993 14.3776 8.04385 13.3683 6.99965C12.3581 5.95544 12.1968 3 10.5 3Z'
                            fill='#FFC224'
                          ></path>
                        </svg>
                        {doctor.Rating}
                      </RatingWrapper>
                    </DetailWrapper>
                  </Card>
                </Link>
              </SwiperSlide>
            ))}
          </Swiper>
        </SwiperContainer>
      </main>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  const response = await fetch(
    "https://api-dev.cura.healthcare/DoctorsListings/",
  );
  const data = await response.json();

  return {
    props: {
      doctors: data.Result.splice(0, 10),
    },
  };
};

export default Home;
